services:
  authservice:
    image: authservice:latest
    ports:
      - target: 8082
        published: 8082
        protocol: tcp
        mode: host
    networks:
      - telegram-parser-network
    privileged: true
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
networks:
  telegram-parser-network:
    driver: overlay
    attachable: true
