google:
  client_id: "will-be-loaded-from-env"
  client_secret: "will-be-loaded-from-env"
  redirect_url: "http://localhost:8082/api/v1/callback?provider=google"
  scopes:
    - "openid"
    - "https://www.googleapis.com/auth/userinfo.email"
github:
  client_id: "will-be-loaded-from-env"
  client_secret: "will-be-loaded-from-env"
  redirect_url: "http://localhost:8082/api/v1/callback?provider=github"
  scopes:
    - "user:email"
telegram:
  token: "will-be-loaded-from-env"
  redirect_url: "http://localhost:8082/api/v1/callback?provider=telegram"
  scopes:
    - "profile"
jwt:
  secret: "will-be-loaded-from-env"
  session_id_expires_in: 604800
enabled_providers:
  - google
  - github
  - telegram_bot
  - telegram_widget
