environment: "local"
http_server:
  address: ":8082"
  timeout: 10s
  idle_timeout: 120s
logger:
  level: 0
  format: "console"
cors:
  allowed_origins:
    - "*"
kafka:
  brokers:
    - "127.0.0.1:9092"
  auth_topic: "auth-events"
  timeout:
    write: 10s
    read: 10s
  retry:
    max_attempts: 3
    backoff: 1s
